//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DTP()
        {
            this.DTP_Driver = new HashSet<DTP_Driver>();
        }
    
        public int Id { get; set; }
        public string NameStreet { get; set; }
        public int NumberHome { get; set; }
        public string RoadSection { get; set; }
        public string TrafficLane { get; set; }
        public string MoreDetails { get; set; }
        public int CountVictims { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTP_Driver> DTP_Driver { get; set; }
    }
}
