//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTP_Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DTP_Driver()
        {
            this.Photo_DTPDriver = new HashSet<Photo_DTPDriver>();
        }
    
        public int Id { get; set; }
        public System.Guid IdDriver { get; set; }
        public int IdDtp { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual DTP DTP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo_DTPDriver> Photo_DTPDriver { get; set; }
    }
}
