//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licences
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Licences()
        {
            this.StatusHistory = new HashSet<StatusHistory>();
        }
    
        public int Id { get; set; }
        public System.Guid IdGuidDriver { get; set; }
        public System.DateTime LicenceDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public string Categories { get; set; }
        public int LicenceSeries { get; set; }
        public int LicenceNumber { get; set; }
        public string VIN { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Color { get; set; }
        public string TypeOfDrive { get; set; }
        public int IdStatus { get; set; }
        public string CarNumber { get; set; }
        public Nullable<int> IdRegion { get; set; }
    
        public virtual CarColors CarColors { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual LicenceStatus LicenceStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusHistory> StatusHistory { get; set; }
        public virtual Regions Regions { get; set; }
    }
}
