//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo_DTPDriver
    {
        public int Id { get; set; }
        public int IdDTPDriver { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual DTP_Driver DTP_Driver { get; set; }
    }
}
